/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Display;

import Other.ChiTietHoaDon;
import Other.DAOChiTietHoaDon;
import Other.DialogHelper;
import Other.HoaDon;
import Other.MaSPAndSoLuong;
import Other.MaSPAndSoLuongDAO;
import Other.MyCombobox;
import com.orsoncharts.plot.PiePlot3D;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

public class CTHoaDon extends javax.swing.JFrame {

    DAOChiTietHoaDon hd = new DAOChiTietHoaDon();
    MaSPAndSoLuongDAO hdThongKe = new MaSPAndSoLuongDAO();
    String dburl = "jdbc:sqlserver://localhost;databaseName=Milk_Tea&FoodS;user=java3;password=java";

    /**
     * Creates new form CTHoaDon
     */
    public CTHoaDon() {
        ImageIcon img = new ImageIcon("src//Image//iced-tea.png");
        this.setIconImage(img.getImage());
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        load();
        setLocationRelativeTo(this);
    }

    void load() {
        DefaultTableModel model = (DefaultTableModel) tblCTHD2.getModel();
        model.setRowCount(0);

        List<ChiTietHoaDon> list = hd.select();

        try {
            for (ChiTietHoaDon item : list) {
                Object[] row = {
                    item.getMaChiTietHD(),
                    item.getMaHD(),
                    item.getMaSP(),
                    item.getSoLuong(),
                    item.getThanhTien(),
                    item.getKichThuoc()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void loadSoLuong_MaSP() {
        DefaultTableModel model = (DefaultTableModel) tblThongKe.getModel();
        model.setRowCount(0);

        List<MaSPAndSoLuong> list = hdThongKe.select();

        try {
            for (MaSPAndSoLuong item : list) {
                Object[] row = {
                    item.getMaSP(),
                    item.getSoLuong()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBarChart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTHD2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        btnPieChart = new javax.swing.JButton();

        btnBarChart.setText("Bar Chart");
        btnBarChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarChartActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHI TIẾT HÓA ĐƠN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblCTHD2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ma CTHD", "Ma HD", "Ma SP", "So Luong", "Thanh Tien", "Kich Thuoc"
            }
        ));
        jScrollPane1.setViewportView(tblCTHD2);

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(tblThongKe);

        btnPieChart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPieChart.setText("Biểu đồ xu hướng mua hàng");
        btnPieChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPieChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPieChart)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(btnPieChart)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.load();
        this.loadSoLuong_MaSP();
    }//GEN-LAST:event_formWindowOpened

    private void btnBarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarChartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarChartActionPerformed

    private void btnPieChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPieChartActionPerformed
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        List<MaSPAndSoLuong> list = hdThongKe.select();
        try {
            for (MaSPAndSoLuong item : list) {
                pieDataset.setValue(String.valueOf(item.getMaSP()), 
                        item.getSoLuong());
            }
            JFreeChart chart = ChartFactory.createPieChart("Biểu "
                    + "đồ xu hướng mua hàng", pieDataset, true, true, true);
            PiePlot p = (PiePlot) chart.getPlot();
            ChartFrame frame = new ChartFrame("Biểu đồ xu hướng mua hàng", chart);
            frame.setVisible(true);
            frame.setSize(450, 500);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        } catch (Exception e) {
            e.printStackTrace();
            DialogHelper.alert(this, "Lỗi hiện thị biểu đồ.");
        }
    }//GEN-LAST:event_btnPieChartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTHoaDon().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarChart;
    private javax.swing.JButton btnPieChart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCTHD2;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables
}
